### PR TITLE
Treat empty value of prop as true when using [Boolean, String] types

### LINKED ISSUE #91: Interpret empty string as Boolean in props
I've noticed, that props, that are supposed to be `true` or some string value, doesn't work as `true` when specifying only the name of prop. 

For example

This is not working:
```html
<sui-table basic>...</sui-table>
```

You have to do it like this:
```html
<sui-table :basic="true">...</sui-table>
```

I think it must work in first case also

### PR DESCRIPTION
**Pull request by ArStah**
Hi @mariolamacchia, look how i suggest to resolve #91 issue.
What do you say about it? Should i embed this solution to all components?

### CODE REVIEW

**Comment by mariolamacchia** [comment]
I'm not really fond of adding so much complexity to a simple function. Note that the problem is not with *every* boolean, but only with the props that can be either boolean or string (basically that have `type: [Boolean, String]`).

I'd rather add a utility function (eg `isTrue`). What are your thoughts?

**Comment by ArStah** [comment]
This method also makes possible do not do:
```js
classes(
   this.propName && `${this.popName} someClass`
)
```
But just:
```js
classes(
  [this.propName, 'someClass']
);
```
And also i do not say to change every entry like that, but only the ones, that can have empty or some other values, that are supposed to be inserted as class

**Comment by ArStah** [comment]
But if not, yes, we can do some function as `isTrue` in utils

**Comment by ArStah** [comment]
That's funny, but before in Vue it [was treated](https://github.com/vuejs/vue/issues/4538) like we need, but then they change it

**Comment by ArStah** [comment]
I've created [PR](https://github.com/vuejs/vue/pull/7583), so, after it will be merged, or will be found other solution, the following commits will be a solution

**Comment by mariolamacchia** [comment]
Looks like we can merge this now, right?

**Comment by ArStah** [comment]
Yep, but i'll update Vue again, since there is a hotfix

**Pull request merged**
