### PR TITLE
Fix listeners

### LINKED ISSUE #59: Events should work without `.native` modifier
At the moment you need to add the `.native` modifier for events to work: https://jsfiddle.net/y1d73jpz/

We can update the `getChildProps` function to get all listeners from the parent component so that we won't need it anymore. Here is how our friends at Vuetify fixed it: https://github.com/vuetifyjs/vuetify/blob/a3ca27526c08a45f17a41510ab3f67bde7a039ca/src/mixins/routable.js#L37

### PR DESCRIPTION
**Pull request by mariolamacchia**
Fixes #59 

I added the option to override the listeners to the solution by @tesarwijaya.

Now, if like @ArStah said [here](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/pull/65#issuecomment-366505785), there is a custom event to catch, it's possible to prevent inheriting with `this.generateListeners({ myCustomEvent: null })`

### CODE REVIEW

**Comment by mariolamacchia** [comment]
You don't have access to the component definition from the mixin, but to the component instance. That `events` isn't stored anywhere

**Comment by ArStah** [comment]
@mariolamacchia no, you have, [look](https://codepen.io/anon/pen/oEMNbK)

**Comment by mariolamacchia** [comment]
Damn, I wasn't checking the prototype. Thanks for the heads up

**Comment by ArStah** [comment]
Great, wait little bit with embeding it to the all of components until i'll finish #123

**Comment by mariolamacchia** [comment]
I updated it. The events can be stored in the component like this: 
```js
export default {
  name: 'SuiComponent',
  events: {
    customEvent1: {
      description: 'This is the description',
    },
  },
}
```

I was thinking: maybe sometimes we want to add a native event to the docs (eg `click` for the `SuiButton`). What do you think of:

```js
export default {
  name: 'SuiComponent',
  events: {
    click: {
      description: 'Fired when clicking the button',
    },
    customEvent1: {
      description: 'This is a custom event',
      custom: true, // this prevents the event to be passed to the root element
    },
  },
}
```

**Comment by ArStah** [comment]
@mariolamacchia yep, i think it's good idea

**Comment by mariolamacchia** [comment]
oops just read your message... what's the problem in embedding the mixin now?

**Comment by ArStah** [comment]
Because i'm refactoring almost all the components, so to avoid merge conflicts)

**Pull request merged**
