### PR TITLE
77 remove has class and has attribute in unit tests

### PR DESCRIPTION
**Pull request by BoyWithSilverWings**
Removing `hasClass()` and replacing with `classes()` for all `elements`. 
Specs in modules and views are yet to be done.

### CODE REVIEW

**Comment by mariolamacchia** [comment]
Thanks @BoyWithSilverWings! You can see [here](https://travis-ci.org/Semantic-UI-Vue/Semantic-UI-Vue/pull_requests) if there are still some errors showing up

**Comment by BoyWithSilverWings** [comment]
@mariolamacchia I have removed `hasClass` from all tests in elements folder. The rest of the folders are yet to be done.

**Comment by BoyWithSilverWings** [comment]
- Removed `hasClass` from all elements in `modules` folder. 
- Removed `hasClass` from utils

`views` folder is left.

**Comment by BoyWithSilverWings** [comment]
@mariolamacchia You have any idea why these tests are failing? They are working fine when I run on local. :confused:

**Comment by mariolamacchia** [comment]
[Here](https://travis-ci.org/Semantic-UI-Vue/Semantic-UI-Vue/builds/338315864?utm_source=github_status&utm_medium=notification) is the log, it looks like `attributes().src` returns `undefined`

**Comment by BoyWithSilverWings** [comment]
It surely looks so. But the same code runs without errors on my local machine. What is different in production?
image

**Comment by mariolamacchia** [comment]
Here is the problem.  https://github.com/vuejs/vue-test-utils/issues/263

It works locally because you aren't using yarn but npm, I guess. I upgraded the dependency, can you merge master and push, please?

**Comment by BoyWithSilverWings** [comment]
@mariolamacchia Done.

**Pull request merged**
