### PR TITLE
[WIP] create listeners mixins and add it to button component

### PR DESCRIPTION
**Pull request by tesarwijaya**
hello @mariolamacchia 
i create a simple mixins to help removing `.native` modifier as referred #59.
i am only applying it to button component for now, i would like to see your opinion with this methods.

### CODE REVIEW

**Comment by mariolamacchia** [comment]
@tesarwijaya Is this still WIP?

**Comment by tesarwijaya** [comment]
i only applied this mixins to button component. if you like this approach i will apply it to other needed components.
also i get curious why you didn't create getPropsChild as a mixins? is there any consideration behind?

**Comment by mariolamacchia** [comment]
Sorry I missed your first comment. Your approach is great 👍 

> also i get curious why you didn't create getPropsChild as a mixins? is there any consideration behind?

There is no consideration behind it. Actually, it might be a good idea to create a common mixin that will be applied to all components and to use that to remove the `.native` too. What do you think?

**Comment by tesarwijaya** [comment]
sorry i had been very busy on December, i didn't have any spare time to looked up this PR.
i would like to do it too, so what components should we implement this mixin?

**Comment by mariolamacchia** [comment]
No worries! Actually, let's take a step at the time. This mixin alone looks good for now, we can deal with the getPropsChild in a separate PR. Just ping me when you think this is ready to be merged

**Comment by ArStah** [comment]
Hey guys, what's up with this PR?

**Comment by mariolamacchia** [comment]
@tesarwijaya ^^

**Comment by ArStah** [comment]
@mariolamacchia what about merging this PR? I will add the `generateListeners` to the rest components.

**Comment by mariolamacchia** [comment]
I'm working on this one, wIll merge today

**Comment by ArStah** [comment]
@mariolamacchia, sooo?

**Comment by ArStah** [comment]
I have a doubt about this approach...
Seems it passing any event, assigned to a component to it's root element which can be unwanted in some cases, For example, if we have a custom event, that called `change`, and the root element is `<input>` so when `change` event caused on the `<input>` - event listener will be called twice.
What about creating an option named `events` in each component, that will contain all event names that this component can emit?. This will solve this problem, because we can filter listeners and pass only those, that can't be fired by the component, and also using this option we can represent and describe in docs, what events can be fired by the component

**Comment by mariolamacchia** [comment]
Replaced by #118

**Pull request closed without merging**
